In [1]:
import pandas as pd

In [50]:
df10=pd.read_excel("rainfalldata/2010-Vellore District Rainfall.xlsx",sheet_name=[0,1,2,3,4,5,6,7,8,9,10,11,12])
df11=pd.read_excel("rainfalldata/2011-Vellore District Rainfall.xlsx")
df12=pd.read_excel("rainfalldata/2012-Vellore District Rainfall.xlsx")

In [51]:
df10[0]

,VELLORE DISTRICT RAINFALL REPORT JANUARY - 2010,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Date,Alangayam,Ambur,Arakkonam,Arcot,Gudiyatham,Melalathur,Sholingur,Tirupattur,Vaniyambadi,Vellore,Wallajah,Total,Avg
2,2010-01-01 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
3,2010-01-02 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
4,2010-01-03 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
5,2010-01-04 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
6,2010-01-05 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
7,2010-01-06 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
8,2010-01-07 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
9,2010-01-08 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
10,2010-01-09 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
11,2010-01-10 00:00:00,-,-,-,-,2.6,2,-,2,-,-,-,6.6,0.6
12,2010-01-11 00:00:00,-,-,-,-,11.4,7.2,-,1.5,-,44.8,-,64.9,5.9
13,2010-01-12 00:00:00,-,-,-,-,-,-,20,-,-,-,-,20,1.81818
14,2010-01-13 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
15,2010-01-14 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
16,2010-01-15 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
17,2010-01-16 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
18,2010-01-17 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
19,2010-01-18 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
20,2010-01-19 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
21,2010-01-20 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
22,2010-01-21 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
23,2010-01-22 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
24,2010-01-23 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
25,2010-01-24 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
26,2010-01-25 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
27,2010-01-26 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
28,2010-01-27 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
29,2010-01-28 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
30,2010-01-29 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
31,2010-01-30 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
32,2010-01-31 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
33,Total,0,0,0,0,14,9.2,20,3.5,0,44.8,0,91.5,8.31818
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,District Overall monthly Total,NaN,NaN,91.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,District Overall monthly Avg,NaN,NaN,8.31818,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
df10[0].columns=df10[0].iloc[1,0:]
df10[0]

1,Date,Alangayam,Ambur,Arakkonam,Arcot,Gudiyatham,Melalathur,Sholingur,Tirupattur,Vaniyambadi,Vellore,Wallajah,Total,Avg
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Date,Alangayam,Ambur,Arakkonam,Arcot,Gudiyatham,Melalathur,Sholingur,Tirupattur,Vaniyambadi,Vellore,Wallajah,Total,Avg
2,2010-01-01 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
3,2010-01-02 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
4,2010-01-03 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
5,2010-01-04 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
6,2010-01-05 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
7,2010-01-06 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
8,2010-01-07 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
9,2010-01-08 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
10,2010-01-09 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
11,2010-01-10 00:00:00,-,-,-,-,2.6,2,-,2,-,-,-,6.6,0.6
12,2010-01-11 00:00:00,-,-,-,-,11.4,7.2,-,1.5,-,44.8,-,64.9,5.9
13,2010-01-12 00:00:00,-,-,-,-,-,-,20,-,-,-,-,20,1.81818
14,2010-01-13 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
15,2010-01-14 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
16,2010-01-15 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
17,2010-01-16 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
18,2010-01-17 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
19,2010-01-18 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
20,2010-01-19 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
21,2010-01-20 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
22,2010-01-21 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
23,2010-01-22 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
24,2010-01-23 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
25,2010-01-24 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
26,2010-01-25 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
27,2010-01-26 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
28,2010-01-27 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
29,2010-01-28 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
30,2010-01-29 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
31,2010-01-30 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
32,2010-01-31 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
33,Total,0,0,0,0,14,9.2,20,3.5,0,44.8,0,91.5,8.31818
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,District Overall monthly Total,NaN,NaN,91.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,District Overall monthly Avg,NaN,NaN,8.31818,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
df10[0]

1,Alangayam,Ambur,Arakkonam,Arcot,Gudiyatham,Kaveripakkam,Melalathur,Sholingur,Tirupattur,Vaniyambadi,Vellore,Wallajah,Total,Avg
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Date,Alangayam,Ambur,Arakkonam,Arcot,Gudiyatham,Melalathur,Sholingur,Tirupattur,Vaniyambadi,Vellore,Wallajah,Total,Avg
2,2010-01-01 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
3,2010-01-02 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
4,2010-01-03 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
5,2010-01-04 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
6,2010-01-05 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
7,2010-01-06 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
8,2010-01-07 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
9,2010-01-08 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
10,2010-01-09 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
11,2010-01-10 00:00:00,-,-,-,-,2.6,2,-,2,-,-,-,6.6,0.6
12,2010-01-11 00:00:00,-,-,-,-,11.4,7.2,-,1.5,-,44.8,-,64.9,5.9
13,2010-01-12 00:00:00,-,-,-,-,-,-,20,-,-,-,-,20,1.81818
14,2010-01-13 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
15,2010-01-14 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
16,2010-01-15 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
17,2010-01-16 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
18,2010-01-17 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
19,2010-01-18 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
20,2010-01-19 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
21,2010-01-20 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
22,2010-01-21 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
23,2010-01-22 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
24,2010-01-23 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
25,2010-01-24 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
26,2010-01-25 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
27,2010-01-26 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
28,2010-01-27 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
29,2010-01-28 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
30,2010-01-29 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
31,2010-01-30 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
32,2010-01-31 00:00:00,-,-,-,-,-,-,-,-,-,-,-,0,0
33,Total,0,0,0,0,14,9.2,20,3.5,0,44.8,0,91.5,8.31818
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,District Overall monthly Total,NaN,NaN,91.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,District Overall monthly Avg,NaN,NaN,8.31818,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
for row,frame in df10[0].iterrows():
    print(frame["Arcot"])

nan
Arcot
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
0
nan
nan
nan